import { Scan, Finding, Target, Report, NotificationItem, CorrelationItem, UserProfile } from '@/types';

export const initialUserProfile: UserProfile = {
  name: 'Maria Tariq',
  email: 'maria.tariq@secops.enterprise.org',
  role: 'Senior Security Analyst',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  twoFactorEnabled: true,
  aiProvider: 'GPT-4o Security Engine',
  defaultScanType: 'Standard Assessment',
  defaultIntensity: 'Standard',
  notifications: {
    scanCompleted: true,
    criticalFound: true,
    reportGenerated: true,
  },
};

export const initialTargets: Target[] = [
  {
    id: 'TGT-001',
    name: 'OWASP Juice Shop',
    url: 'http://juice-shop.local',
    environment: 'Staging',
    description: 'Internal staging instance of e-commerce application for vulnerability assessment testing.',
    authorized: true,
    lastScanDate: '01 Oct 2026',
    lastScanId: 'SCAN-2026-0012',
    riskLevel: 'High',
    status: 'Active',
    findingsCount: 23,
  },
  {
    id: 'TGT-002',
    name: 'Acme Core Banking API',
    url: 'https://api.acme-corp.com',
    environment: 'Production',
    description: 'Core microservices gateway handling client balance and fund transfer endpoints.',
    authorized: true,
    lastScanDate: '02 Oct 2026',
    lastScanId: 'SCAN-2026-0015',
    riskLevel: 'Medium',
    status: 'Under Scan',
    findingsCount: 14,
  },
  {
    id: 'TGT-003',
    name: 'Damn Vulnerable Web App (DVWA)',
    url: 'http://dvwa.internal',
    environment: 'Testing',
    description: 'Isolated testbed environment for benchmarking automated scanner accuracy and false positives.',
    authorized: true,
    lastScanDate: '28 Sep 2026',
    lastScanId: 'SCAN-2026-0011',
    riskLevel: 'Critical',
    status: 'Active',
    findingsCount: 38,
  },
  {
    id: 'TGT-004',
    name: 'Storefront Portal QA',
    url: 'https://staging.storefront.io',
    environment: 'Development',
    description: 'Pre-production frontend customer portal for automated pipeline regression scans.',
    authorized: true,
    lastScanDate: '22 Sep 2026',
    lastScanId: 'SCAN-2026-0008',
    riskLevel: 'Medium',
    status: 'Active',
    findingsCount: 8,
  },
  {
    id: 'TGT-005',
    name: 'Identity & SSO Provider',
    url: 'https://auth.acme-corp.com',
    environment: 'Production',
    description: 'OAuth 2.0 / OpenID Connect authentication server protecting customer credentials.',
    authorized: true,
    lastScanDate: '15 Sep 2026',
    lastScanId: 'SCAN-2026-0005',
    riskLevel: 'Low',
    status: 'Active',
    findingsCount: 4,
  },
  {
    id: 'TGT-006',
    name: 'Customer Support Desk',
    url: 'https://support.acme-corp.com',
    environment: 'Staging',
    description: 'Zendesk bridge application for ticketing and customer query ingestion.',
    authorized: true,
    lastScanDate: '10 Sep 2026',
    lastScanId: 'SCAN-2026-0003',
    riskLevel: 'Low',
    status: 'Active',
    findingsCount: 6,
  },
  {
    id: 'TGT-007',
    name: 'Internal Admin Telemetry',
    url: 'http://telemetry.internal.net',
    environment: 'Development',
    description: 'Grafana & Prometheus observability dashboard endpoint.',
    authorized: true,
    lastScanDate: '04 Sep 2026',
    lastScanId: 'SCAN-2026-0001',
    riskLevel: 'Medium',
    status: 'Active',
    findingsCount: 11,
  },
  {
    id: 'TGT-008',
    name: 'Billing Gateway Service',
    url: 'https://pay.acme-corp.com',
    environment: 'Production',
    description: 'PCI-DSS scoped microservice integrating payment gateway tokens.',
    authorized: true,
    lastScanDate: '29 Aug 2026',
    lastScanId: 'SCAN-2026-0002',
    riskLevel: 'Low',
    status: 'Active',
    findingsCount: 3,
  },
];

export const initialFindings: Finding[] = [
  {
    id: 'FND-1001',
    scanId: 'SCAN-2026-0012',
    title: 'SQL Injection in User Authentication',
    severity: 'High',
    riskScore: 9.2,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/rest/user/login',
    source: 'OWASP ZAP',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Critical Priority',
    cve: 'CWE-89',
    cwe: 'Improper Neutralization of Special Elements used in an SQL Command',
    description: 'The authentication endpoint accepts user-supplied data in the email field that is concatenated directly into an SQLite database query without parameterized preparation or type sanitization.',
    whyItMatters: 'An unauthenticated attacker can manipulate database queries to bypass authentication completely, extract sensitive password hashes, or execute arbitrary database modifications leading to total account takeover.',
    evidence: `POST /rest/user/login HTTP/1.1
Host: juice-shop.local
Content-Type: application/json

{"email": "' OR 1=1 --", "password": "random_password"}

--- RESPONSE ---
HTTP/1.1 200 OK
Content-Type: application/json
Set-Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
{"status":"success","data":{"id":1,"email":"admin@juice-sh.op","role":"admin"}}`,
    technicalDetails: 'SQL syntax injection verified via Boolean-based blind evaluation and error response reflection. The server executes raw string template: SELECT * FROM Users WHERE email = \'' + '${req.body.email}' + '\' AND password = ...',
    riskAnalysis: 'Receives CVSS 9.2 (Critical/High) because it is remotely exploitable without authentication, requires low attack complexity, and results in complete loss of confidentiality, integrity, and authentication bypass.',
    recommendedAction: 'Replace string concatenation with parameterized SQL queries (Prepared Statements) using Sequelize / Knex ORM bindings. Avoid direct raw query execution.',
    aiExplanation: 'The application appears vulnerable to SQL injection because user input is directly interpolated into a raw database query statement rather than being handled as discrete query parameters. This allows syntax breakout using standard quotes and SQL comment sequences.',
    aiRemediation: [
      'Refactor the login authentication query to utilize Parameterized Statements: db.models.User.findOne({ where: { email: req.body.email } })',
      'Implement strict input validation on the email parameter using an RFC 5322 compliant regex before query dispatch',
      'Enforce least-privilege database user permissions so the application service account cannot modify table schemas or access administrative system tables',
      'Apply an Application Firewall (WAF) rule to inspect and block typical SQL metacandidate characters in JSON payload keys'
    ],
    correlatedWith: ['FND-1004'],
  },
  {
    id: 'FND-1002',
    scanId: 'SCAN-2026-0012',
    title: 'Reflected Cross-Site Scripting (XSS)',
    severity: 'High',
    riskScore: 8.7,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/#/search?q=',
    source: 'OWASP ZAP',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Critical Priority',
    cve: 'CWE-79',
    cwe: 'Improper Neutralization of Input During Web Page Generation',
    description: 'The search query parameter `q` is reflected into the Document Object Model (DOM) and rendered as inner HTML without contextual entity encoding or sanitization.',
    whyItMatters: 'Malicious actors can craft a specially encoded link and trick victims into clicking it, allowing execution of arbitrary JavaScript within the context of the user\'s session, resulting in session hijacking and credential theft.',
    evidence: `GET /#/search?q=%3Ciframe%20src%3D%22javascript%3Aalert(1)%22%3E HTTP/1.1
Host: juice-shop.local

--- DOM SINK EXECUTION ---
document.querySelector('#search-query').innerHTML = decodeURIComponent(location.hash);
Triggered alert(1) in browser context.`,
    technicalDetails: 'Untrusted input flows from source `window.location.search` / hash directly into sink `element.innerHTML` in search-result.component.ts.',
    riskAnalysis: 'Score 8.7 based on CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:H/I:L/A:N. Enables arbitrary script execution on authenticated user sessions with high confidentiality impact.',
    recommendedAction: 'Use framework-native safe DOM bindings (such as Angular text interpolation or React JSX text) or sanitize HTML via DOMPurify before inserting into the DOM.',
    aiExplanation: 'The client-side single page application extracts query parameters directly from the URL and passes them to an insecure DOM sink (`innerHTML`) without neutral encoding. When a user navigates to an attacker-controlled search link, the injected script executes automatically.',
    aiRemediation: [
      'Replace innerHTML assignment with textContent or safe interpolation: element.textContent = searchQuery',
      'Sanitize any intended rich HTML markup using DOMPurify.sanitize(userInput)',
      'Deploy a robust Content-Security-Policy (CSP) header: script-src \'self\'; object-src \'none\''
    ],
  },
  {
    id: 'FND-1003',
    scanId: 'SCAN-2026-0012',
    title: 'Insecure Direct Object Reference (IDOR) in Basket',
    severity: 'High',
    riskScore: 8.4,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/api/BasketItems/2',
    source: 'Custom Check',
    status: 'In Review',
    date: '01 Oct 2026',
    priority: 'High Priority',
    cve: 'CWE-639',
    cwe: 'Authorization Bypass Through User-Controlled Key',
    description: 'The API retrieves and modifies shopping cart items based on an incrementing integer ID provided in the URL path, without verifying whether the requesting user owns the basket.',
    whyItMatters: 'An authenticated user can view, edit, or empty another customer\'s cart, inspect item prices, and tamper with order quantities by simply altering the basket ID parameter.',
    evidence: `PUT /api/BasketItems/2 HTTP/1.1
Host: juice-shop.local
Authorization: Bearer <User_A_Token>
Content-Type: application/json

{"quantity": 10}

--- RESPONSE ---
HTTP/1.1 200 OK
{"status":"success","data":{"id":2,"BasketId":1,"ProductId":3,"quantity":10}}
Note: Basket 1 belongs to user B (admin), yet user A successfully modified it.`,
    riskAnalysis: 'High severity (8.4) due to missing object-level authorization (BOLA/IDOR), directly compromising customer privacy and transaction integrity.',
    recommendedAction: 'Implement server-side ownership validation in the basket controller: verify that Basket.userId matches req.user.id before executing modifications.',
    aiExplanation: 'The application relies solely on basic token authentication at the route level, but fails to check authorization permissions on the specific record ID referenced in the request path.',
    aiRemediation: [
      'Enforce an authorization check: if (basketItem.Basket.UserId !== currentUser.id) return res.status(403).json({ error: "Access Denied" })',
      'Adopt non-sequential random identifiers such as UUIDv4 or encrypted hash IDs for resource references'
    ],
  },
  {
    id: 'FND-1004',
    scanId: 'SCAN-2026-0012',
    title: 'Database Error Information Disclosure',
    severity: 'Medium',
    riskScore: 5.3,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/rest/user/login',
    source: 'Custom Check',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Medium Priority',
    cve: 'CWE-209',
    cwe: 'Generation of Error Message Containing Sensitive Information',
    description: 'When invalid SQL characters are submitted to the login form, the server responds with a detailed stack trace and raw SQLite error messages containing table and column names.',
    whyItMatters: 'Detailed database errors assist attackers in mapping the internal database schema, accelerating the crafting of functional SQL injection exploits.',
    evidence: `HTTP/1.1 500 Internal Server Error
Content-Type: text/html

SQLITE_ERROR: near "admin": syntax error in SELECT * FROM Users WHERE email = 'admin' OR 1=1' AND deletedAt IS NULL
at Database.prepare (/juice-shop/node_modules/sqlite3/lib/sqlite3.js:52:17)`,
    riskAnalysis: 'Medium severity (5.3) as it discloses schema metadata that fuels correlated exploitation of the authentication SQL injection vulnerability.',
    recommendedAction: 'Catch database exceptions and return generic error messages to clients (e.g. "An unexpected error occurred"). Log detailed stack traces exclusively to internal logging streams.',
    aiExplanation: 'The backend development error handler is active in an exposed environment. Detailed database exception strings are passed directly into the HTTP response body rather than being sanitized by a global exception filter.',
    aiRemediation: [
      'Configure NODE_ENV=production to suppress verbose stack traces',
      'Implement an Express error-handling middleware that strips internal runtime details before responding to the client'
    ],
    correlatedWith: ['FND-1001'],
  },
  {
    id: 'FND-1005',
    scanId: 'SCAN-2026-0012',
    title: 'Insecure Session Cookie: Missing SameSite & Secure Flags',
    severity: 'Medium',
    riskScore: 6.1,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/rest/user/login',
    source: 'OWASP ZAP',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Medium Priority',
    cve: 'CWE-614',
    cwe: 'Sensitive Cookie in HTTPS Session Without Secure Attribute',
    description: 'The authentication session cookie (`token`) is issued without the `Secure`, `HttpOnly`, and `SameSite` flags configured.',
    whyItMatters: 'Without `HttpOnly`, cookies are readable by malicious scripts during an XSS attack. Without `Secure`, cookies can be intercepted over unencrypted HTTP. Without `SameSite`, the application is susceptible to Cross-Site Request Forgery (CSRF).',
    evidence: `Set-Cookie: token=eyJhbGciOi...; Path=/;
Flags observed: None.
Expected: HttpOnly; Secure; SameSite=Strict`,
    riskAnalysis: 'Medium severity (6.1). Degrades defense-in-depth and multiplies the exploitability of any Cross-Site Scripting or transport interception weaknesses.',
    recommendedAction: 'Configure the cookie session generator to set `Secure`, `HttpOnly`, and `SameSite=Lax` or `Strict`.',
    aiExplanation: 'Session cookies without security flags remain accessible to JavaScript in the browser context and can be transmitted over plain HTTP if a user accidentally follows a non-TLS link.',
    aiRemediation: [
      'Update cookie options in cookie-session: res.cookie("token", val, { httpOnly: true, secure: true, sameSite: "lax" })',
      'Ensure the server terminates TLS properly and redirects all HTTP traffic to HTTPS'
    ],
  },
  {
    id: 'FND-1006',
    scanId: 'SCAN-2026-0012',
    title: 'Missing Content-Security-Policy (CSP) Header',
    severity: 'Medium',
    riskScore: 6.5,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/*',
    source: 'HTTP Headers',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Medium Priority',
    cve: 'CWE-1021',
    cwe: 'Improper Restriction of Rendered UI Layers or Scripts',
    description: 'The HTTP response headers do not include a Content-Security-Policy definition, allowing inline scripts, eval statements, and external script injection.',
    whyItMatters: 'Without a CSP, modern browser defense mechanisms against Cross-Site Scripting (XSS), clickjacking, and unauthorized resource embedding are disabled.',
    evidence: `HTTP/1.1 200 OK
Server: Express
Content-Type: text/html; charset=UTF-8
Missing Header: Content-Security-Policy`,
    riskAnalysis: 'Medium severity (6.5). While not a vulnerability by itself, the absence of CSP removes the critical secondary containment layer for XSS.',
    recommendedAction: 'Implement a Content-Security-Policy header restricting script execution to approved domain origins and forbidding inline script evaluation.',
    aiExplanation: 'The server does not specify which domains and resource types the browser is permitted to load. A strong CSP policy restricts the impact of script injection flaws.',
    aiRemediation: [
      'Install Helmet middleware in Express: app.use(helmet.contentSecurityPolicy())',
      'Define directive: default-src \'self\'; script-src \'self\'; style-src \'self\' \'unsafe-inline\'; object-src \'none\''
    ],
  },
  {
    id: 'FND-1007',
    scanId: 'SCAN-2026-0012',
    title: 'Weak TLS 1.0 and TLS 1.1 Protocols Enabled',
    severity: 'Medium',
    riskScore: 5.8,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '443/TCP',
    source: 'TLS Check',
    status: 'In Review',
    date: '01 Oct 2026',
    priority: 'Medium Priority',
    cve: 'CWE-326',
    cwe: 'Inadequate Encryption Strength',
    description: 'The web server TLS configuration negotiates deprecated TLS 1.0 and TLS 1.1 handshake protocols containing known cipher vulnerabilities (BEAST, POODLE).',
    whyItMatters: 'Adversaries performing man-in-the-middle network attacks can downgrade user connections to deprecated protocols and attempt cryptographic interception.',
    evidence: `TLS Handshake Analysis:
[+] TLSv1.0: ENABLED (Cipher: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA)
[+] TLSv1.1: ENABLED (Cipher: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA)
[+] TLSv1.2: ENABLED
[+] TLSv1.3: ENABLED`,
    riskAnalysis: 'Medium severity (5.8). Non-compliant with PCI-DSS 3.2.1 standards and modern web transport security baselines.',
    recommendedAction: 'Disable TLS 1.0 and TLS 1.1 in web server/reverse proxy configuration. Permit only TLS 1.2 and TLS 1.3 with forward-secret cipher suites.',
    aiExplanation: 'Older TLS protocols utilize CBC-mode ciphers susceptible to padding oracle attacks. Modern browsers have deprecated TLS 1.0/1.1; maintaining them increases attack surface.',
    aiRemediation: [
      'Update Nginx / Apache SSL settings: ssl_protocols TLSv1.2 TLSv1.3;',
      'Configure modern cipher list: ssl_ciphers HIGH:!aNULL:!MD5:!3DES;'
    ],
  },
  {
    id: 'FND-1008',
    scanId: 'SCAN-2026-0012',
    title: 'Exposed SSH Port 22 with Legacy Daemon',
    severity: 'Low',
    riskScore: 3.2,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '22/TCP',
    source: 'Nmap',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Low Priority',
    cve: 'CWE-200',
    cwe: 'Exposure of Sensitive Information to an Unauthorized Actor',
    description: 'Nmap network discovery identified TCP Port 22 open on the target host running OpenSSH 7.4p1.',
    whyItMatters: 'Exposing administrative management ports directly to the public web invites automated brute-force attacks and password spraying.',
    evidence: `PORT   STATE SERVICE VERSION
22/tcp open  ssh     OpenSSH 7.4p1 Debian 10+deb9u7 (protocol 2.0)
|_ssh-hostkey: 2048 77:a2:15:3e:b4:... (RSA)`,
    riskAnalysis: 'Low severity (3.2). While SSH requires authentication, public accessibility of port 22 provides an unnecessary vector for remote brute force.',
    recommendedAction: 'Restrict port 22 access using firewall IP whitelisting or place SSH access behind a secure VPN gateway.',
    aiExplanation: 'The target machine has its management SSH port reachable from external interfaces. Hardening network boundaries prevents brute force and zero-day exposure.',
    aiRemediation: [
      'Configure iptables or security group to allow SSH only from internal bastion jump hosts',
      'Disable password authentication in sshd_config: PasswordAuthentication no'
    ],
  },
  {
    id: 'FND-1009',
    scanId: 'SCAN-2026-0012',
    title: 'Missing HTTP Strict Transport Security (HSTS)',
    severity: 'Low',
    riskScore: 3.8,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/*',
    source: 'HTTP Headers',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Low Priority',
    cve: 'CWE-319',
    cwe: 'Cleartext Transmission of Sensitive Information',
    description: 'The server does not return the Strict-Transport-Security header to enforce secure HTTPS-only client communication.',
    whyItMatters: 'Users making initial requests via http:// can be intercepted via SSL-stripping attacks before the redirect to HTTPS completes.',
    evidence: `HTTP/1.1 200 OK
Missing Header: Strict-Transport-Security`,
    riskAnalysis: 'Low risk (3.8). Easily remediated configuration gap that leaves initial connections vulnerable to active network interception.',
    recommendedAction: 'Send Strict-Transport-Security: max-age=31536000; includeSubDomains; preload in all HTTPS responses.',
    aiExplanation: 'HSTS instructs browsers never to contact the domain over insecure HTTP. Without this header, malicious Wi-Fi networks can downgrade traffic.',
    aiRemediation: [
      'Add HSTS header in reverse proxy: Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"'
    ],
  },
  {
    id: 'FND-1010',
    scanId: 'SCAN-2026-0012',
    title: 'Clickjacking Protection Missing (X-Frame-Options)',
    severity: 'Low',
    riskScore: 3.5,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/',
    source: 'HTTP Headers',
    status: 'Resolved',
    date: '01 Oct 2026',
    priority: 'Low Priority',
    cve: 'CWE-1021',
    cwe: 'Improper Restriction of Rendered UI Layers or Frames',
    description: 'Neither X-Frame-Options nor CSP frame-ancestors is present on web responses.',
    whyItMatters: 'Allows external malicious web pages to frame the web application inside a transparent iframe to perform clickjacking attacks.',
    evidence: `Response headers lack X-Frame-Options: DENY / SAMEORIGIN`,
    riskAnalysis: 'Low severity (3.5). Resolved in latest patch staging rollout.',
    recommendedAction: 'Add X-Frame-Options: SAMEORIGIN header.',
    aiExplanation: 'Frame-busting or frame-ancestor constraints prevent third-party domains from embedding your application inside invisible overlays.',
    aiRemediation: [
      'Configure X-Frame-Options: SAMEORIGIN',
      'Add frame-ancestors \'self\' to CSP'
    ],
  },
  {
    id: 'FND-1011',
    scanId: 'SCAN-2026-0012',
    title: 'Web Server Banner Version Disclosure',
    severity: 'Low',
    riskScore: 2.8,
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    endpoint: '/',
    source: 'Custom Check',
    status: 'Open',
    date: '01 Oct 2026',
    priority: 'Low Priority',
    cve: 'CWE-200',
    cwe: 'Information Exposure Through Server Header',
    description: 'Server returns exact runtime software and operating system version in the HTTP Server response header.',
    whyItMatters: 'Provides automated reconnaissance bots with immediate knowledge of potential known CVEs for specific version numbers.',
    evidence: `Server: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1
X-Powered-By: Express`,
    riskAnalysis: 'Low risk (2.8). Standard reconnaissance reduction practice.',
    recommendedAction: 'Mask or disable the Server and X-Powered-By header.',
    aiExplanation: 'Leaking web server and OS versions reduces the time required for an attacker to correlate known exploits.',
    aiRemediation: [
      'Set ServerTokens Prod and ServerSignature Off in Apache',
      'Run app.disable("x-powered-by") in Express'
    ],
  },
];

export const initialCorrelations: CorrelationItem[] = [
  {
    id: 'CORR-01',
    title: 'Authentication SQL Injection & Schema Information Leakage',
    source1: {
      tool: 'OWASP ZAP',
      finding: 'SQL Injection in /rest/user/login (Parameter: email)',
      evidence: 'Boolean blind logic returned 200 OK for payload: admin@juice-sh.op\' OR 1=1--',
    },
    source2: {
      tool: 'Custom Python Check',
      finding: 'SQLite Database Error Stack Trace Leakage',
      evidence: 'Stack trace leaked: SQLITE_ERROR: near "admin": syntax error in SELECT * FROM Users...',
    },
    commonIssue: 'Unsanitized user input concatenation in auth database query + unprotected runtime error reflection',
    consolidatedFinding: 'Verified Exploitable Authentication Bypass via SQL Injection (CVSS 9.2 Critical)',
    deduplicationRatio: '2 scanner alerts merged into 1 prioritized root cause incident',
    riskScore: 9.2,
    status: 'Confirmed Exploitable',
  },
  {
    id: 'CORR-02',
    title: 'Cross-Site Scripting (XSS) & Unprotected Content Security Policy',
    source1: {
      tool: 'OWASP ZAP',
      finding: 'Reflected XSS on /#/search?q=',
      evidence: 'Injected script executed payload via DOM innerHTML sink',
    },
    source2: {
      tool: 'HTTP Headers Scanner',
      finding: 'Missing Content-Security-Policy (CSP) Header',
      evidence: 'No CSP header present to restrict script execution or report violations',
    },
    commonIssue: 'Lack of client-side output encoding combined with absent defense-in-depth CSP perimeter',
    consolidatedFinding: 'High-Impact Uncontained Cross-Site Scripting Vulnerability (CVSS 8.7 High)',
    deduplicationRatio: 'Combined vulnerability vector + missing safeguard merged',
    riskScore: 8.7,
    status: 'High Priority Remediation',
  },
];

export const samplePipelineStages = (status: 'Running' | 'Completed' | 'Pending' = 'Completed') => [
  {
    id: 'stage-1',
    name: 'Nmap — Network Discovery',
    description: 'Host discovery, open port enumeration, OS fingerprinting, and service detection.',
    tool: 'Nmap 7.94',
    status: 'Completed' as const,
    progress: 100,
    duration: '42s',
    findingsCount: 2,
  },
  {
    id: 'stage-2',
    name: 'OWASP ZAP — Web Security Testing',
    description: 'Active spidering, automated vulnerability scanning (SQLi, XSS, CSRF, Auth flaws).',
    tool: 'OWASP ZAP 2.14.0',
    status: status === 'Running' ? ('Running' as const) : ('Completed' as const),
    progress: status === 'Running' ? 62 : 100,
    duration: status === 'Running' ? '1m 45s (Elapsed)' : '2m 14s',
    findingsCount: status === 'Running' ? 8 : 12,
  },
  {
    id: 'stage-3',
    name: 'Custom Security Checks',
    description: 'Targeted Python scripts for API authorization flaws, IDOR, and sensitive leakage.',
    tool: 'WebSec Python Suite',
    status: status === 'Running' ? ('Pending' as const) : ('Completed' as const),
    progress: status === 'Running' ? 0 : 100,
    duration: status === 'Running' ? '--' : '38s',
    findingsCount: 4,
  },
  {
    id: 'stage-4',
    name: 'Finding Processing & Normalization',
    description: 'Deduplication across tools, CVSS v3.1 scoring normalization, and schema alignment.',
    tool: 'WebSec Normalizer',
    status: status === 'Running' ? ('Pending' as const) : ('Completed' as const),
    progress: status === 'Running' ? 0 : 100,
    duration: status === 'Running' ? '--' : '15s',
    findingsCount: 0,
  },
  {
    id: 'stage-5',
    name: 'Multi-Tool Risk Correlation',
    description: 'Correlation matrix connecting port discoveries with web endpoints and error disclosures.',
    tool: 'Correlation Engine',
    status: status === 'Running' ? ('Pending' as const) : ('Completed' as const),
    progress: status === 'Running' ? 0 : 100,
    duration: status === 'Running' ? '--' : '12s',
    findingsCount: 2,
  },
  {
    id: 'stage-6',
    name: 'AI Analysis & Remediation Generation',
    description: 'Generates evidence-backed explanations, context-aware remediation, and code fixes.',
    tool: 'GPT-4o Security Engine',
    status: status === 'Running' ? ('Pending' as const) : ('Completed' as const),
    progress: status === 'Running' ? 0 : 100,
    duration: status === 'Running' ? '--' : '21s',
    findingsCount: 0,
  },
];

export const initialScans: Scan[] = [
  {
    id: 'SCAN-2026-0012',
    targetUrl: 'http://juice-shop.local',
    targetName: 'OWASP Juice Shop',
    environment: 'Staging',
    modules: [
      'Nmap Network Discovery',
      'OWASP ZAP Web Security Scan',
      'HTTP Security Headers',
      'TLS Configuration',
      'Information Leakage Checks',
      'Custom Security Checks',
    ],
    intensity: 'Standard',
    status: 'Completed',
    progress: 100,
    currentStage: 'Assessment Completed',
    startTime: '01 Oct 2026 14:22:10',
    endTime: '01 Oct 2026 14:26:22',
    duration: '4m 12s',
    findingsCount: 23,
    criticalCount: 2,
    highCount: 6,
    mediumCount: 10,
    lowCount: 5,
    infoCount: 0,
    overallRisk: 'HIGH',
    riskScore: 7.8,
    authorized: true,
    pipeline: samplePipelineStages('Completed'),
    logs: [
      { id: '1', timestamp: '14:22:10', level: 'INFO', stage: 'Nmap', message: 'Initialized network scan against host 192.168.1.104' },
      { id: '2', timestamp: '14:22:35', level: 'INFO', stage: 'Nmap', message: 'Discovered open ports: 22/tcp (ssh), 80/tcp (http), 3000/tcp (http-alt)' },
      { id: '3', timestamp: '14:22:52', level: 'SUCCESS', stage: 'Nmap', message: 'Network discovery phase completed in 42s' },
      { id: '4', timestamp: '14:22:53', level: 'INFO', stage: 'OWASP ZAP', message: 'Spider crawl identified 142 endpoints and 48 web forms' },
      { id: '5', timestamp: '14:24:12', level: 'WARN', stage: 'OWASP ZAP', message: 'Potential SQL Injection confirmed at /rest/user/login via parameter email' },
      { id: '6', timestamp: '14:25:07', level: 'WARN', stage: 'OWASP ZAP', message: 'Reflected XSS confirmed at /#/search?q=' },
      { id: '7', timestamp: '14:25:08', level: 'INFO', stage: 'Custom Checks', message: 'Executing proprietary API Authorization and IDOR test suites' },
      { id: '8', timestamp: '14:25:46', level: 'INFO', stage: 'Normalizer', message: 'Aggregated 27 raw alerts. Normalized into 23 distinct vulnerability records' },
      { id: '9', timestamp: '14:26:01', level: 'SUCCESS', stage: 'Correlation Engine', message: 'Correlated SQL Injection alert with SQLite stack disclosure finding' },
      { id: '10', timestamp: '14:26:22', level: 'SUCCESS', stage: 'AI Analysis', message: 'AI remediation synthesis completed for all confirmed findings' },
    ],
  },
  {
    id: 'SCAN-2026-0015',
    targetUrl: 'https://api.acme-corp.com',
    targetName: 'Acme Core Banking API',
    environment: 'Production',
    modules: [
      'Nmap Network Discovery',
      'OWASP ZAP Web Security Scan',
      'HTTP Security Headers',
      'TLS Configuration',
    ],
    intensity: 'Standard',
    status: 'Running',
    progress: 62,
    currentStage: 'OWASP ZAP — Web Security Testing',
    startTime: '02 Oct 2026 21:30:00',
    duration: '2m 10s (Running)',
    findingsCount: 14,
    criticalCount: 0,
    highCount: 3,
    mediumCount: 7,
    lowCount: 4,
    infoCount: 0,
    overallRisk: 'MEDIUM',
    riskScore: 5.6,
    authorized: true,
    pipeline: samplePipelineStages('Running'),
    logs: [
      { id: '101', timestamp: '21:30:01', level: 'INFO', stage: 'System', message: 'Assessment launched with explicit authorized credentials' },
      { id: '102', timestamp: '21:30:20', level: 'INFO', stage: 'Nmap', message: 'Port 443/tcp open, TLS 1.3 negotiated' },
      { id: '103', timestamp: '21:30:45', level: 'SUCCESS', stage: 'Nmap', message: 'Host discovery completed cleanly' },
      { id: '104', timestamp: '21:31:00', level: 'INFO', stage: 'OWASP ZAP', message: 'Active scanning initiated for REST API definitions' },
      { id: '105', timestamp: '21:32:04', level: 'WARN', stage: 'OWASP ZAP', message: 'Insecure cookie flag detected on session tokens' },
    ],
  },
  {
    id: 'SCAN-2026-0011',
    targetUrl: 'http://dvwa.internal',
    targetName: 'Damn Vulnerable Web App (DVWA)',
    environment: 'Testing',
    modules: [
      'Nmap Network Discovery',
      'OWASP ZAP Web Security Scan',
      'HTTP Security Headers',
      'Custom Security Checks',
    ],
    intensity: 'Comprehensive',
    status: 'Completed',
    progress: 100,
    currentStage: 'Assessment Completed',
    startTime: '28 Sep 2026 10:14:00',
    endTime: '28 Sep 2026 10:24:18',
    duration: '10m 18s',
    findingsCount: 38,
    criticalCount: 5,
    highCount: 12,
    mediumCount: 15,
    lowCount: 6,
    infoCount: 0,
    overallRisk: 'CRITICAL',
    riskScore: 9.4,
    authorized: true,
    pipeline: samplePipelineStages('Completed'),
    logs: [],
  },
  {
    id: 'SCAN-2026-0008',
    targetUrl: 'https://staging.storefront.io',
    targetName: 'Storefront Portal QA',
    environment: 'Development',
    modules: [
      'HTTP Security Headers',
      'TLS Configuration',
      'OWASP ZAP Web Security Scan',
    ],
    intensity: 'Basic',
    status: 'Completed',
    progress: 100,
    currentStage: 'Assessment Completed',
    startTime: '22 Sep 2026 16:02:11',
    endTime: '22 Sep 2026 16:05:44',
    duration: '3m 33s',
    findingsCount: 8,
    criticalCount: 0,
    highCount: 1,
    mediumCount: 4,
    lowCount: 3,
    infoCount: 0,
    overallRisk: 'MEDIUM',
    riskScore: 5.2,
    authorized: true,
    pipeline: samplePipelineStages('Completed'),
    logs: [],
  },
  {
    id: 'SCAN-2026-0005',
    targetUrl: 'https://auth.acme-corp.com',
    targetName: 'Identity & SSO Provider',
    environment: 'Production',
    modules: ['TLS Configuration', 'HTTP Security Headers'],
    intensity: 'Basic',
    status: 'Completed',
    progress: 100,
    currentStage: 'Assessment Completed',
    startTime: '15 Sep 2026 09:00:00',
    endTime: '15 Sep 2026 09:02:15',
    duration: '2m 15s',
    findingsCount: 4,
    criticalCount: 0,
    highCount: 0,
    mediumCount: 1,
    lowCount: 3,
    infoCount: 0,
    overallRisk: 'LOW',
    riskScore: 3.1,
    authorized: true,
    pipeline: samplePipelineStages('Completed'),
    logs: [],
  },
];

export const initialReports: Report[] = [
  {
    id: 'REP-2026-0012',
    scanId: 'SCAN-2026-0012',
    target: 'OWASP Juice Shop',
    targetUrl: 'http://juice-shop.local',
    date: '01 Oct 2026',
    duration: '4m 12s',
    findingsCount: 23,
    riskLevel: 'High',
    riskScore: 7.8,
    status: 'Ready',
    executiveSummary: 'Automated multi-tool assessment completed for OWASP Juice Shop staging environment. Identified 23 confirmed security issues, including 2 critical authentication bypass and injection flaws. Immediate remediation is strongly advised before production cutover.',
  },
  {
    id: 'REP-2026-0011',
    scanId: 'SCAN-2026-0011',
    target: 'Damn Vulnerable Web App (DVWA)',
    targetUrl: 'http://dvwa.internal',
    date: '28 Sep 2026',
    duration: '10m 18s',
    findingsCount: 38,
    riskLevel: 'Critical',
    riskScore: 9.4,
    status: 'Ready',
    executiveSummary: 'Comprehensive vulnerability benchmark scan detected multiple unconstrained command injections, SQL injections, and weak cryptographic configurations.',
  },
  {
    id: 'REP-2026-0008',
    scanId: 'SCAN-2026-0008',
    target: 'Storefront Portal QA',
    targetUrl: 'https://staging.storefront.io',
    date: '22 Sep 2026',
    duration: '3m 33s',
    findingsCount: 8,
    riskLevel: 'Medium',
    riskScore: 5.2,
    status: 'Ready',
    executiveSummary: 'Routine sprint development assessment revealed missing defense-in-depth HTTP headers and permissive cookie policies.',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Scan completed',
    message: 'Juice Shop assessment completed with 23 findings.',
    timestamp: '10 minutes ago',
    read: false,
    type: 'scan_completed',
    link: '/scans/SCAN-2026-0012',
  },
  {
    id: 'notif-2',
    title: 'High-risk finding detected',
    message: 'A critical SQL Injection vulnerability was confirmed on /rest/user/login.',
    timestamp: '14 minutes ago',
    read: false,
    type: 'high_risk',
    link: '/findings/FND-1001',
  },
  {
    id: 'notif-3',
    title: 'Report generated',
    message: 'Security assessment report REP-2026-0012 is ready for download.',
    timestamp: '25 minutes ago',
    read: true,
    type: 'report_ready',
    link: '/reports/REP-2026-0012',
  },
];

export const trendData = [
  { date: '10 Sep', findings: 12, scans: 2 },
  { date: '14 Sep', findings: 19, scans: 3 },
  { date: '18 Sep', findings: 15, scans: 1 },
  { date: '22 Sep', findings: 28, scans: 4 },
  { date: '26 Sep', findings: 22, scans: 3 },
  { date: '29 Sep', findings: 38, scans: 5 },
  { date: '01 Oct', findings: 23, scans: 4 },
];

export const riskDistributionData = [
  { label: 'Critical', count: 2, percentage: 8.7, color: '#dc2626' },
  { label: 'High', count: 6, percentage: 26.1, color: '#ea580c' },
  { label: 'Medium', count: 10, percentage: 43.5, color: '#f59e0b' },
  { label: 'Low', count: 5, percentage: 21.7, color: '#10b981' },
  { label: 'Informational', count: 0, percentage: 0, color: '#0284c7' },
];
