'use client';

import React, { useState } from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { Card, CardHeader, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { SeverityBadge } from '@/components/ui/Badge';
import { CodeBlock } from '@/components/ui/CodeBlock';
import { useApp } from '@/context/AppContext';
import {
  BrainCircuit,
  Sparkles,
  Info,
  CheckCircle2,
  AlertTriangle,
  Flame,
  ShieldCheck,
  Search,
  Filter,
  ExternalLink,
} from 'lucide-react';

export default function AIAnalysisPage() {
  const { findings, setSelectedFinding } = useApp();
  const [selectedSeverity, setSelectedSeverity] = useState('All');
  const [searchQuery, setSearchQuery] = useState('');

  const filteredFindings = findings.filter((f) => {
    const matchesSev = selectedSeverity === 'All' || f.severity === selectedSeverity;
    const matchesQuery =
      f.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      f.aiExplanation.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesSev && matchesQuery;
  });

  return (
    <DashboardLayout
      title="AI Security Analysis"
      subtitle="Evidence-based explanation of confirmed findings and remediation guidance"
    >
      <div className="space-y-6">
        {/* Section 32: AI Transparency Banner */}
        <div className="p-4 sm:p-5 rounded-2xl bg-gradient-to-r from-blue-900 via-slate-900 to-cyan-950 text-white shadow-lg border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-start sm:items-center gap-3.5">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/20 text-cyan-400 flex items-center justify-center shrink-0 border border-cyan-500/30">
              <BrainCircuit className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <span>AI Advisory Engine Active</span>
                <span className="text-[10px] font-mono bg-cyan-400/20 text-cyan-300 px-2 py-0.5 rounded-full border border-cyan-400/30 font-semibold">
                  GPT-4o Security Baseline
                </span>
              </h3>
              <p className="text-xs text-slate-300 mt-1 leading-relaxed max-w-2xl">
                <strong>AI Transparency Notice:</strong> AI analyzes confirmed security findings generated by automated scanners (Nmap, OWASP ZAP, Custom Checks) and does not independently perform vulnerability scanning.
              </p>
            </div>
          </div>
          <div className="shrink-0 flex items-center gap-2">
            <span className="text-xs text-slate-400 font-mono">Model Latency: 1.2s</span>
          </div>
        </div>

        {/* Filter Bar */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 bg-white p-4 rounded-xl border border-slate-200">
          <div className="relative w-full sm:w-80">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
            <input
              type="text"
              placeholder="Search AI analyses, explanations..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full text-xs pl-9 pr-3 py-2 rounded-lg border border-slate-300 focus:outline-none focus:ring-2 focus:ring-blue-500/20"
            />
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <span className="text-xs font-semibold text-slate-500">Severity:</span>
            {['All', 'High', 'Medium', 'Low'].map((sev) => (
              <button
                key={sev}
                onClick={() => setSelectedSeverity(sev)}
                className={`text-xs px-3 py-1.5 rounded-lg font-medium transition-all ${
                  selectedSeverity === sev
                    ? 'bg-blue-600 text-white shadow-xs'
                    : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                }`}
              >
                {sev}
              </button>
            ))}
          </div>
        </div>

        {/* Section 31: AI Analysis Cards */}
        <div className="space-y-6">
          {filteredFindings.map((finding) => (
            <Card
              key={finding.id}
              className="border border-slate-200/90 shadow-sm overflow-hidden hover:shadow-md transition-shadow"
            >
              {/* Card Header with severity & title */}
              <div className="px-6 py-4 bg-slate-50/70 border-b border-slate-100 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <SeverityBadge severity={finding.severity} size="md" />
                  <div>
                    <h3 className="text-base font-bold text-slate-900">{finding.title}</h3>
                    <div className="flex items-center gap-2 text-xs text-slate-400 font-mono mt-0.5">
                      <span>Endpoint: {finding.endpoint}</span>
                      <span>•</span>
                      <span>Detection: {finding.source}</span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="text-right">
                    <span className="text-[10px] uppercase font-bold text-slate-400 block font-mono">
                      Risk Score
                    </span>
                    <span className="text-sm font-mono font-bold text-rose-600">
                      {finding.riskScore.toFixed(1)} / 10
                    </span>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setSelectedFinding(finding)}
                  >
                    View Finding Drawer
                  </Button>
                </div>
              </div>

              {/* Card Body */}
              <CardContent className="p-6 space-y-5">
                {/* 1. AI Explanation */}
                <div>
                  <h4 className="text-xs font-bold text-cyan-900 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                    <Sparkles className="w-3.5 h-3.5 text-cyan-600" />
                    AI Vulnerability Explanation
                  </h4>
                  <div className="p-4 rounded-xl bg-cyan-50/40 border border-cyan-100 text-xs text-slate-800 leading-relaxed font-sans">
                    {finding.aiExplanation}
                  </div>
                </div>

                {/* 2. Why It Matters */}
                <div>
                  <h4 className="text-xs font-bold text-amber-900 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                    <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
                    Why It Matters (Impact)
                  </h4>
                  <p className="text-xs text-slate-600 leading-relaxed bg-amber-50/30 p-3.5 rounded-xl border border-amber-100">
                    {finding.whyItMatters}
                  </p>
                </div>

                {/* 3. Evidence Used by AI */}
                <div>
                  <h4 className="text-xs font-bold text-slate-800 uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
                    <Flame className="w-3.5 h-3.5 text-rose-500" />
                    Evidence Ingested by AI Parser
                  </h4>
                  <CodeBlock
                    code={finding.evidence}
                    title={`Scanner Payload: ${finding.source}`}
                    language="http"
                  />
                </div>

                {/* 4. Recommended Fix */}
                <div>
                  <h4 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                    <ShieldCheck className="w-4 h-4 text-emerald-600" />
                    AI Recommended Remediation Roadmap
                  </h4>
                  <div className="space-y-2">
                    {finding.aiRemediation.map((step, idx) => (
                      <div
                        key={idx}
                        className="flex items-start gap-3 p-3 rounded-xl bg-white border border-slate-200 text-xs shadow-2xs"
                      >
                        <span className="w-5 h-5 rounded-full bg-blue-100 text-blue-700 font-bold font-mono text-[11px] flex items-center justify-center shrink-0 mt-0.5">
                          {idx + 1}
                        </span>
                        <span className="text-slate-700 font-medium leading-relaxed">
                          {step}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
}
